# Generated by Django 4.1.4 on 2022-12-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_sell_car_payment_driver_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental_Car_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_car_id', models.CharField(max_length=5)),
                ('user_profile_id', models.CharField(max_length=5)),
                ('transition_id', models.CharField(max_length=15)),
            ],
        ),
    ]
