# Generated by Django 4.1.4 on 2022-12-13 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_rental_car_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rent_Car_Payment',
        ),
    ]
